title: Your Portfolio Title
logo: /assets/img/headshot_cirle.png
description: A portfolio showcasing my work in data science and machine learning.
show_downloads: true
#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
#theme: jekyll-theme-cayman.gemspec
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
social:
  - title: GitHub
    url: github.com/Vey27?tab=repositories /Vey27
  - title: LinkedIn
    url: https://linkedin.com/in/vey-d-20b27a119/in/Vey Damneun
  - title: datascienceportfol
    url: https://www.datascienceportfol.io/Vey
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.33.1/gradio.js"
></script>

<gradio-app src="https://veyvey-covidsentiment.hf.space"></gradio-app>

<iframe
	src="https://veyvey-covidsentiment.hf.space"
	frameborder="0"
	width="850"
	height="450"
></iframe>

## Gradio Application

{% raw %}
<iframe src="https://veyvey-covidsentiment.hf.space" width="100%" height="600px" frameborder="0" allowfullscreen></iframe>
{% endraw %}
